dragonflydb/documentation

docusaurus.config.js, package.json, yarn.lock
Had to upgrade Docusaurus to get it set up.
=> Setup Google Tag Manager

docs/getting-started/docker.md
Signed-off-by: Nick Gottlieb <ngottlieb1@gmail.com>
=> add docker install

docusaurus.config.js, package.json, src/css/custom.css, yarn.lock
This is the quickest solution right now.
This is a temporary solution until we are eligible for the Algolia Docsearch:
=> Temporary local search implementation

docs/managing-dragonfly/replication.md
=> fix: rename DragonflyDB to Dragonfly

docs/command-reference/server-management/save.md
Documentation for https://github.com/dragonflydb/dragonfly/pull/1028
=> Document SAVE options

docs/managing-dragonfly/backups.md
=> Document backup options

docs/command-reference/server-management/role.md
for dragonflydb/dragonfly/issues/1146
=> Small fix in ROLE documentation

docs/getting-started/binary.md, docs/getting-started/docker.md, docs/getting-started/kubernetes-operator.md
Fixes https://github.com/dragonflydb/documentation/issues/86
This PR adds memory and cpu requirements to the docs.
=> feat(install): Add minimum requirements to docs

docs/about/about.md
=> fix: spelling in `about.md`

docs/managing-dragonfly/scripting.md
=> Lua scripting guide

docs/command-reference/strings/cl.throttle.md
Document CL.THROTTLE, close #63
=> Document CL.THROTTLE

README.md, docs/about/about.md, docs/about/faq.md, docs/command-reference/sorted-sets/zadd.md, docs/development/sdks.md, docs/getting-started/binary.md, docs/getting-started/docker-compose.md, docs/getting-started/docker.md, docs/getting-started/getting-started.md, docs/getting-started/kubernetes-operator.md, docs/getting-started/kubernetes.md
fixes a few typos and rephrases the text here and there
=> fixes typos and other minor edits

docs/command-reference/server-management/hello.md
=> hello command add supported flags

docs/command-reference/compatibility.md, src/css/custom.css
Changed compatibility table from json data to markdown syntax
=> Compatibility table markdown added

docs/command-reference/server-management/info.md
- Address https://github.com/dragonflydb/documentation/issues/118 for formatting.
=> fix: INFO command formatting & adjustments

docs/managing-dragonfly/using-tls.md
=> Add a guide for TLS certificates.

docs/command-reference/compatibility.md
- `HMSET` should be updated as fully supported.
=> [Compatibility] HMSET

docs/command-reference/acl/_category_.yml, docs/command-reference/acl/deluser.md, docs/command-reference/acl/list.md, docs/command-reference/acl/setuser.md, docs/command-reference/acl/whoami.md, docs/command-reference/compatibility.md, docs/command-reference/geospatial-indices/_category_.yml, docs/command-reference/json/json.debug-fields.md, docs/command-reference/json/json.debug-help.md, docs/command-reference/json/json.del.md, docs/command-reference/json/json.get.md, docs/command-reference/json/json.set.md, docs/command-reference/json/json.strappend.md, docs/command-reference/pubsub/_category_.yml, docs/command-reference/server-management/_category_.yml, docs/command-reference/server-management/config-get.md, docs/command-reference/server-management/config-set.md, docs/command-reference/server-management/config.md, docs/command-reference/sorted-sets/_category_.yml, docs/command-reference/sorted-sets/bzpopmax.md, docs/command-reference/sorted-sets/bzpopmin.md
=> [Commands] Add/update doc for a few commands

docs/command-reference/stream/xack.md, docs/command-reference/stream/xreadgroup.md
- Covers https://github.com/dragonflydb/documentation/issues/125
- Bring in `XREADGROUP` doc with adjustments.
=> feat(stream): add docs for `XREADGROUP`

docs/command-reference/compatibility.md, docs/command-reference/stream/xinfo-consumers.md, docs/command-reference/stream/xinfo-stream.md
fixes https://github.com/dragonflydb/documentation/issues/168
=> feat(STREAMS): update documentation to fully support XINFO

docs/managing-dragonfly/backups.md
~~Note not yet released, but will be supported in `v1.11.0`~~
=> feat(backups): add cloud storage section

docs/command-reference/json/json.arrappend.md, docs/command-reference/json/json.arrindex.md, docs/command-reference/json/json.arrinsert.md, docs/command-reference/json/json.arrlen.md, docs/command-reference/json/json.arrpop.md
- Update RESP links for JSON commands.
- Also want to re-trigger Vercel deployment.
=> fix: update RESP links for JSON commands

docs/managing-dragonfly/operator/grafana-guide.md
=> feat(operator): add grafana integration page

docs/managing-dragonfly/cluster-mode.md
=> Document how to set up a real cluster

docs/command-reference/compatibility.md, docs/command-reference/geospatial-indices/geosearch.md, docs/command-reference/server-management/slowlog-get.md, docs/command-reference/server-management/slowlog-help.md, docs/command-reference/server-management/slowlog-len.md, docs/command-reference/server-management/slowlog-reset.md, docs/command-reference/server-management/slowlog.md
In addition, update the compatibility table.
=> Add slowlog and geosearch commands

docs/command-reference/generic/stick.md
Adds docs for our STICK command
=> feat: STICK command docs

docs/managing-dragonfly/using-http.md
=> chore: add http docs 

docs/managing-dragonfly/flags.md
resolves #106
* add docs for config flags
=> chore(flags): add docs for config flags

docs/managing-dragonfly/flags.md
addresses https://github.com/dragonflydb/dragonfly/issues/2081
=> chore: mention c_rehash in ca_cert_dir flag description

docs/command-reference/strings/incr.md, docs/getting-started/docker.md, docs/integrations/integrations.md, docs/integrations/sidekiq.md, docs/managing-dragonfly/flags.md
* add integration docs for sidekiq
* update flag docs
=> chore: add sidekiq docs and update flags

docs/managing-dragonfly/using-tls.md
=> fix: using-tls.md

docusaurus.config.js
added two configs in docusarus.config.js
```
showLastUpdateAuthor: true,
showLastUpdateTime: true,
```
=> feat: add last updated author and time

docs/managing-dragonfly/operator/dragonfly-configuration.md
=> fix(operator): update configuration docs

docs/command-reference/acl/deluser.md, docs/command-reference/acl/dryrun.md, docs/command-reference/acl/getuser.md, docs/command-reference/acl/whoami.md, docs/command-reference/bloom-filter/bf.add.md, docs/command-reference/bloom-filter/bf.exists.md, docs/command-reference/bloom-filter/bf.madd.md, docs/command-reference/bloom-filter/bf.mexists.md, docs/command-reference/bloom-filter/bf.reserve.md, docs/command-reference/geospatial-indices/geoadd.md, docs/command-reference/geospatial-indices/geodist.md, docs/command-reference/geospatial-indices/geohash.md, docs/command-reference/geospatial-indices/geopos.md, docs/command-reference/sorted-sets/zdiff.md, docs/command-reference/strings/cl.throttle.md
Please merge after the following Dragonfly PRs are merged.
- https://github.com/dragonflydb/dragonfly/pull/2943
- https://github.com/dragonflydb/dragonfly/pull/2945)
=> chore: adjustments for some ACL commands

docs/managing-dragonfly/operator/dragonfly-configuration.md
We recently released operator `v1.1.3`. Update the doc accordingly.
=> fix(operator): update configuration page with latest changes

docs/cloud/connections.md, docs/cloud/datastores.md, docs/cloud/getting-started.md, docs/cloud/networks.md, docs/getting-started/cloud.md, docs/getting-started/getting-started.md
=> docs: getting started with cloud

docs/command-reference/compatibility.md
https://github.com/dragonflydb/dragonfly/issues/3161
=> chore: update geosearch compatibility

docs/command-reference/acl/getuser.md, docs/command-reference/acl/list.md, docs/command-reference/acl/setuser.md
=> chore: update acl documentation

docs/command-reference/compatibility.md, docs/command-reference/server-management/client-tracking.md
* add client caching docs
* update client tracking docs
=> feat: add client caching and update tracking docs

docs/managing-dragonfly/flags.md
* update flags to include serialization of big values
=> chore: update flags doc

docs/command-reference/hashes/hsetex.md
refers to [the pr](https://github.com/dragonflydb/dragonfly/pull/3295)
=> feat(hash_family): Add NX option to the HSETEX command

docs/managing-dragonfly/flags.md
=> chore: update serialization_max_chunk_size flag default value

docs/managing-dragonfly/flags.md
* update flag default value
* update description
=> chore: update serialization_max_chunk_size info

docs/managing-dragonfly/scripting.md
Fixes https://github.com/dragonflydb/dragonfly/issues/3512
=> update lua flags

docs/command-reference/acl/getuser.md, docs/command-reference/acl/list.md, docs/command-reference/acl/setuser.md, docs/command-reference/compatibility.md, docs/managing-dragonfly/acl.md
* add docs for pub/sub
* update compatibility page
* update acl docs
=> chore: add missing docs for pub/sub commands and polish

docs/command-reference/strings/append.md, docs/command-reference/strings/bitcount.md, docs/command-reference/strings/bitfield.md, docs/command-reference/strings/bitfield_ro.md, docs/command-reference/strings/bitop.md
Hey @xf10w, I made some suggestions below. Please let me know if they make sense.
If so, you can merge this to your branch first, and then merge your branch. Thanks a lot!
=> chore: new doc format suggestions

docs/command-reference/strings/append.md, docs/command-reference/strings/bitcount.md, docs/command-reference/strings/bitfield.md, docs/command-reference/strings/bitfield_ro.md, docs/command-reference/strings/bitop.md
This sprint covers the following strings commands: append, bitcoin, bitfield, bitfield_ro, bitop
=> Docs Originality Update - Sprint #1

docs/command-reference/strings/bitpos.md, docs/command-reference/strings/cl.throttle.md, docs/command-reference/strings/decr.md, docs/command-reference/strings/decrby.md, docs/command-reference/strings/get.md
This PR updates the following 5 command reference docs: BITPOS, CL.THROTTLE, DECR, DECRBY, GET
=> Docs Originality Update - Batch #2

docs/command-reference/compatibility.md, docs/command-reference/generic/fieldexpire.md, docs/command-reference/hashes/hexpire.md
* add docs for HEXPIRE
* add docs for FIELDEXPIRE
=> chore: add docs for HEXPIRE and FIELDEXPIRE

docs/managing-dragonfly/operator/dragonfly-configuration.md
- add labels field to the doc in Dragonfly Configuration
=> fix(operator): dragonfly.spec.labels is missing in the doc

docs/getting-started/kubernetes.md
dbfilename arg should only contain the filename without any file extensions
=> fix(helm): dbfilename arg extension

docs/command-reference/compatibility.md
* update compatibility support
=> chore: add support docs for sharded pub/sub

docs/command-reference/compatibility.md
* module load is partially supported
=> update: compatibility for modules

docs/cloud/datastores.md
Note we slightly change the cluster mode selector labels to:
- Emulated (Single Shard)
- Swarm (Multi Shard)
=> fix: swarm docs

docs/command-reference/geospatial-indices/georadiusbymember.md
=> chore: add georadiusbymember docs

docs/managing-dragonfly/flags.md
Doc added for the new server flag for aliasing commands.
=> feat(alias): Add docs for alias command

docs/command-reference/compatibility.md
=> chore: update compatibility for CMS commands

docs/command-reference/compatibility.md
=> chore: update BF command compatibility

docs/command-reference/compatibility.md, docs/command-reference/generic/expire.md, docs/command-reference/generic/expireat.md, docs/command-reference/generic/pexpire.md, docs/command-reference/generic/pexpireat.md, docs/command-reference/generic/pexpiretime.md
fixes https://github.com/dragonflydb/documentation/issues/366
fixes https://github.com/dragonflydb/documentation/issues/368
fixes https://github.com/dragonflydb/documentation/issues/367
=> feat: Add flags and examples for commands found missing in fixit

docs/command-reference/compatibility.md, docs/command-reference/generic/randomkey.md
=> chore: Add documentation for `RANDOMKEY`

docs/command-reference/compatibility.md
=> feat: add GETEX into compatibility page

docs/command-reference/compatibility.md, docs/command-reference/hashes/hrandfield.md
=> fix: update HRANDFIELD description

docs/command-reference/server-management/command-info.md
Fixes: https://github.com/dragonflydb/documentation/issues/405
=> chore: COMMAND INFO doc added

docs/command-reference/generic/eval-ro.md
Fixes: https://github.com/dragonflydb/documentation/issues/414
=> chore: EVAL_RO doc added

docs/command-reference/compatibility.md, docs/command-reference/server-management/client-kill.md
Fixes: https://github.com/dragonflydb/documentation/issues/396
=> chore: CLIENT KILL doc added

docs/command-reference/compatibility.md, docs/command-reference/generic/copy.md
fixes https://github.com/dragonflydb/documentation/issues/412
=> docs: Add docs for copy command

docs/command-reference/server-management/flushall.md, docs/command-reference/server-management/flushdb.md
fixes https://github.com/dragonflydb/documentation/issues/406
=> docs: Add options for FLUSHALL

docs/command-reference/sets/srandmember.md
=> feat add srandmember doc

docs/getting-started/kubernetes.md
- Some styling changes for getting started with Helm.
- Make sure the complete list of values is mentioned earlier on the page.
=> chore: helm styling

docs/command-reference/lists/blmove.md
fixes https://github.com/dragonflydb/documentation/issues/326
=> docs: Add blmove

docs/command-reference/sorted-sets/zrandmember.md
=> chore: Add ZRANDMEMBER command

docs/command-reference/json/json.arrappend.md
=> chore: Path in JSON.ARRAPPEND is not optional

docs/command-reference/json/json.get.md
=> chore: Add NOESCAPE option to the JSON.GET documentation

docs/command-reference/compatibility.md, docs/command-reference/sorted-sets/zrangestore.md
=> chore: Add ZRANGESTORE command

docs/command-reference/compatibility.md, docs/command-reference/lists/blmpop.md, docs/command-reference/lists/lmpop.md, docs/command-reference/sorted-sets/bzmpop.md, docs/command-reference/sorted-sets/zmpop.md
=> chore: update BLMPOP compatibility to supported
