dragonflydb/documentation

- docs/getting-started/getting-started.md
- docs/getting-started/kubernetes-operator.md
- docs/getting-started/kubernetes.md
Fixes #74 
This commit adds a new page to the documentation that describes how to
use the Kubernetes operator. This is similar to the existing
README we have in the Operator repo.
> feat(docs): add kubernetes operator documentation

- docs/managing-dragonfly/running-memcached.md
1. Its that brief, should I really add a new page for it?
2. The cache is officially called memcache**d**, maybe we should rename the flag until its too late?
> fix: Mention how to use memcache_port

- docs/command-reference/compatibility.md
- docs/command-reference/sorted-sets/zdiff.md
I implemented `zdiff` a few months back but for some reason we never updated the docs. I noticed today, so I quickly added it here :)
> feat: update docs to include zdiff command

- docs/command-reference/geospatial-indices/_category_.yml
- docs/command-reference/geospatial-indices/geoadd.md
- docs/command-reference/geospatial-indices/geodist.md
- docs/command-reference/geospatial-indices/geohash.md
- docs/command-reference/geospatial-indices/geopos.md
- docs/command-reference/stream/_category_.yml
Add the first batch of GEO commands described here: https://github.com/dragonflydb/documentation/issues/124
- `GEOADD`
- `GEOHASH`
- `GEODIST`
- `GEOPOS`
As for `GEOADD`, I didn't bring in the limits & Earth model sections from [here](https://redis.io/commands/geoadd/), since I need to confirm these with an engineer to make sure they are accurate for Dragonfly as well. However, for tomorrow's release, the current version should be sufficient, IMO. @worldsoup
> feat: update docs to include the first batch of geo commands

- docs/command-reference/compatibility.md
The command is currently unsupported and was not listed in the [API compatibility documentation](https://www.dragonflydb.io/docs/command-reference/compatibility)
- [ZRANGESTORE redis docs](https://redis.io/commands/zrangestore/)
> Add ZRANGESTORE to compatibility table

- docs/migrating-to-dragonfly/01-from-redis-instance/02-sentinel-promotion.md
- Small fix for the wording, should be instance instead of cluster for this section.
> [Migration] Minor fix in Sentinel migration

- docs/getting-started/docker-compose.md
`docker-compose` is the old syntax that doesn't even work anymore without special tweaking while `docker compose` is the recommended way to go
> `docker-compose` -> `docker compose`

- docusaurus.config.js
- Currently the GitHub stars (on the `/docs` page) links to this repo.
- Since it says 21k stars, it should link to the `dragonflydb/dragonfly` repo.
> fix: GitHub stars link to dragonfly instead of documentation

- docs/command-reference/sets/saddex.md
> fix(saddex.md): Simimar typo

- docs/command-reference/compatibility.md
- docs/command-reference/stream/xclaim.md
- docs/command-reference/stream/xpending.md
- https://github.com/dragonflydb/documentation/issues/151 & https://github.com/dragonflydb/documentation/issues/152
- Pulled in docs for `XCLAIM` & `XPENDING`.
- Made adjustments according to Dragonfly server behavior.
- Please use the preview site if that's easier.
> feat(stream): add docs for XCLAIM & XPENDING

- docs/command-reference/compatibility.md
- docs/command-reference/stream/xack.md
- docs/command-reference/stream/xautoclaim.md
- docs/command-reference/stream/xclaim.md
fixes https://github.com/dragonflydb/documentation/issues/160
New commands / options:
XACK
XCLAIM (new last_id option)
XAUTOCLAIM
> Adding doc for new STREAM commands and options

- docs/managing-dragonfly/backups.md
Removes warning about not supporting HTTPS (added in 1.12.0)
> backups: update https support

- docs/managing-dragonfly/flags.md
Just a very quick fix. The param name was updated in https://github.com/dragonflydb/dragonfly/pull/2192/files
> Rename pipeline_queue_limit to subscriber_thread_limit

- docs/command-reference/server-management/client-tracking.md
- docs/integrations/bullmq.md
- docs/integrations/clickhouse.md
- docs/integrations/feast.md
- docs/integrations/integrations.md
- docs/integrations/redlock.md
- docs/integrations/relay.md
- docs/integrations/sidekiq.md
- docs/managing-dragonfly/flags.md
- Add Relay as an integration.
- Add Redlock as an integration.
- Add the `CLIENT TRACKING` command.
---
Note that the Relay blog link is not available until [this PR](https://github.com/dragonflydb/website2/pull/299) is merged.
> feat: add Redlock & Relay

- docs/integrations/bullmq.md
- docs/integrations/clickhouse.md
- docs/managing-dragonfly/scripting.md
- To address https://github.com/taskforcesh/bullmq/issues/2440
> fix: make BullMQ server flags clearer

- docs/managing-dragonfly/acl.md
- docs/managing-dragonfly/aof.md
- docs/managing-dragonfly/append-only.md
- docs/managing-dragonfly/monitoring.md
- docs/managing-dragonfly/operator/grafana-guide.md
- docs/managing-dragonfly/replication.md
- docs/managing-dragonfly/using-http.md
- Fix a typo on the `ACL` page.
- Add more context to the `AOF` page.
- Clean up the `Replication` page a bit.
> chore: some improvements for ACL, AOF, and replication

- docs/command-reference/compatibility.md
- `CLIENT CACHING` should be fully supported after v1.20
- Reformat the API compatibility markdown table.
> chore: update compatibility table

- docs/command-reference/generic/fieldttl.md
Title is wrong and added the disclaimer that exists in `HSETEX`.
I'm also confused about the addition of `FIELDTTL` in `SETEX` - `SETEX` has nothing to do with sets!
In fact, I can't find any commands related to the set expiration mentioned in https://github.com/dragonflydb/dragonfly/pull/3039#issuecomment-2105999667
> fix: FIELDTTL title & add warning about being dragonfly-specific

- docs/managing-dragonfly/operator/dragonfly-configuration.md
The correct setting for the example here is `nodeAffinity`, not `nodeaffinity`. We had an internal user copy this example, which caused a GitOps issue and the setting being ignored.
> fix(operator): Use proper format for affinity example

- docs/managing-dragonfly/using-tls.md
`DRAGONFLY_PASSWORD` when set will crash dragonfly on startup because this environment variable was used to set the password (and now is deprecated). I replaced it such that it doesn't cause any issue.
Addresses: https://github.com/dragonflydb/dragonfly/issues/3994
> chore: replace DRAGONFLY_PASSWORD

- docs/command-reference/strings/cl.throttle.md
- This is temporary.
- Will remove this page and redirect to `/rate-limiter` once the proper way of redirecting is figured out.
> temp: add cl.throttle back in strings

- docs/command-reference/sets/saddex.md
Docs updated for https://www.dragonflydb.io/docs/command-reference/sets/saddex with new option `KEEPTTL`
> feat: Add docs for KEEPTTL in SADDEX command

- docs/command-reference/hashes/hsetex.md
Add docs for the KEEPTTL option added to HSETEX.
updates docs according to https://github.com/dragonflydb/dragonfly/pull/4730
> feat: Add docs for the KEEPTTL option added to HSETEX

- docs/command-reference/compatibility.md
Persist command was misspelled as presist
> Fix typo in compatibility table

- docs/managing-dragonfly/monitoring.md
* Metrics are available on a different port on kubernetes
> docs: Metrics are available on a different port on kubernetes

- docs/command-reference/acl/genpass.md
Adds docs for `acl genpass` command
resolves #371
> chore: acl genpass

- docs/command-reference/server-management/command-count.md
- docs/command-reference/server-management/command-help.md
- docs/command-reference/server-management/command-info.md
- docs/command-reference/server-management/command.md
Fixes: https://github.com/dragonflydb/documentation/issues/397
> fix: Update missing documentation for COMMAND

- docs/command-reference/compatibility.md
- docs/command-reference/geospatial-indices/georadius_ro.md
- docs/command-reference/geospatial-indices/georadiusbymember_ro.md
> feat: add doc for georadius_ro and georadiusbymember_ro

- docs/command-reference/server-management/client-caching.md
- docs/command-reference/server-management/client.md
it seems like compat doc is already updated
fixes https://github.com/dragonflydb/documentation/issues/384
> docs: Add doc for client caching command

- docs/command-reference/server-management/client-pause.md
- docs/command-reference/server-management/flushall.md
- docs/command-reference/server-management/flushdb.md
@dranikpg Can you please check if the description matches the behavior you implemented (https://github.com/dragonflydb/dragonfly/pull/5821)?
- The `FLUSH*` command always deletes keys asynchronously. It only deletes keys that were present at the time the command was invoked. Keys created during the deletion will be unaffected.
- However, if the `SYNC` option is specified, the command waits for the deletion (which is still asynchronous) to finish. Because of this, unlike Redis/Valkey, this command never blocks other commands.
> chore: update FLUSHDB/FLUSHALL options
